#consider it is the infinity distance
INFINITY = 10000

#audio folder
AUDIO_FOLDER = "audio\\"

AUDIO_NUMBER_FOLDER = AUDIO_FOLDER + "numbers\\"

AUDIO_DIGITS_FOLDER = AUDIO_NUMBER_FOLDER + "digits\\"
AUDIO_SUFFIXES_FOLDER = AUDIO_NUMBER_FOLDER + "suffixes\\"

AUDIO_NOTIFICATION_FOLDER = AUDIO_FOLDER + "notification\\"
AUDIO_DETECTED_FOLDER = AUDIO_NOTIFICATION_FOLDER + "detected\\"
AUDIO_UNDETECTED_FOLDER = AUDIO_NOTIFICATION_FOLDER + "undetected\\"

AUDIO_UNIT_FOLDER = AUDIO_FOLDER + "units\\"